# Generated by Django 3.2.8 on 2022-07-01 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contact_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='warnings',
        ),
    ]
